kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-dev-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: argocd-dev

  - kind: ServiceAccount
    name: openshift-gitops-argocd-server
    namespace: argocd-dev
   
  - kind: ServiceAccount
    name: openshift-gitops-argocd-server-test
    namespace: argocd-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
